name: Unit Tests on PR

on:
  pull_request:
    branches:
      - workflow-test
    paths:
      - 'GreenbackPlugin/**'
    
jobs:
  build:
    name: Application Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'GreenbackPlugin'

    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: '@arxum'

      - name: Run MongoDB Container
        uses: wbari/start-mongoDB@v0.2
        with:
          mongoDBVersion: 4.4
          
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN_GITHUB}}
          
      - name: Run tests
        run: npm test
