name: Publish Greenback Plugin

on:
  push:
    branches:
      - workflow-test
    paths:
      - 'NestApp/**'

env:
    VERSION_PREFIX: "0.0."

jobs:
    publish-greenback-client-plugin:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: 'NestApp'

        steps:
        - name: Clone the repository
          uses: actions/checkout@v2

        - name: Setup Node.js environment
          uses: actions/setup-node@v2.4.1
          with:
            node-version: 14
            registry-url: https://npm.pkg.github.com/
            scope: '@arxum'

        - name: Run MongoDB Container
          uses: wbari/start-mongoDB@v0.2
          with:
            mongoDBVersion: 4.4
            
        - name: Install dependencies
          run: npm ci
          env:
            NODE_AUTH_TOKEN: ${{secrets.TOKEN_GITHUB}}
            
        - name: Run tests
          run: npm test

        - name: Export test report to JIRA
          if: always()
          run: echo Exported!
          # uses: mikepenz/xray-action@v2.2.2
          # with:
          #   username: ${{ secrets.XRAY_CLIENT_ID }}
          #   password: ${{ secrets.XRAY_CLIENT_SECRET }}
          #   testFormat: "junit"
          #   testPaths: "**/test-report.xml"
          #   projectKey: "GREEN"

        - name: Bump the package version
          run: npm version ${{ env.VERSION_PREFIX }}$GITHUB_RUN_NUMBER

        - name: Build the package
          run: npm run build
        
        - name: Publish the package
          run: echo Published!
          # run: npm publish
          # env:
          #   NODE_AUTH_TOKEN: ${{secrets.TOKEN_GITHUB}}
