name: Unit Tests

on:
  pull_request:
    branches: [ main ]
    paths: 
    - 'NestApp/**'

jobs:
  build:
    name: Application Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: NestApp

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with: 
          node-version: 14
      - name: Install dependencies
        run: npm ci
        
      - name: Run the tests
        run: npm test

      - name: 1st Stage
        run: echo 1st stage

      - name: 2nd Stage
        run: echo Second stage
