name: Unit Tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Application Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with: 
          node-version: 14
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run the tests
        run: npm test
